/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Resource = {
  _type: "resource";
  type: "article" | "download" | "template" | "link";
  title: string;
  description: string;
  url: string;
};

export type LessonResource = {
  _type: "lessonResource";
  type: "article" | "download" | "template" | "link";
  title: string;
  description: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon: string;
  title: string;
  description: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary: string;
  lessons: Array<{
    _key: string;
  } & LessonReference>;
};

export type CourseModule = {
  _type: "courseModule";
  title: string;
  summary: string;
  lessons: Array<{
    _key: string;
  } & LessonReference>;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  poster?: ContentImage;
  thumbnail?: ContentImage;
  durationSeconds?: number;
  duration?: number;
  freePreview?: boolean;
  studentCount: number;
  notes: PortableText;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<{
    _key: string;
  } & LessonResource | {
    _key: string;
  } & Resource>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: ContentImage;
  icon?: ContentImage;
  level: "beginner" | "intermediate" | "advanced" | "all-levels";
  price: number;
  popular?: boolean;
  studentCount: number;
  learningOutcomes: Array<{
    _key: string;
  } & LearningOutcome>;
  instructor: InstructorReference;
  category: CategoryReference;
  modules: Array<{
    _key: string;
  } & CourseModule | {
    _key: string;
  } & Module>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo: ContentImage;
  expertise: Array<string>;
  bio: PortableText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = PortableText | SanityImageAssetReference | ContentImage | Resource | LessonResource | LearningOutcome | LessonReference | Module | CourseModule | Lesson | Slug | InstructorReference | CategoryReference | Course | Category | Instructor | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[      _type == "course" &&      category._ref == ^._id &&      defined(slug.current)    ])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string;
  courseCount: number;
}>;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    "courses": *[      _type == "course" &&      category._ref == ^._id &&      defined(slug.current)    ] | order(popular desc, title asc) {        _id,  title,  "slug": slug.current,  summary,  coverImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  icon {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  level,  price,  "popular": coalesce(popular, false),  "studentCount": coalesce(studentCount, 0),  category->{    _id,    title,    "slug": slug.current  },  instructor->{    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot }  },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[])    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    };
    icon: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    level: "advanced" | "all-levels" | "beginner" | "intermediate";
    price: number;
    popular: boolean | false;
    studentCount: number;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string>;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      };
    };
    moduleCount: number;
    lessonCount: number;
  }>;
} | null;

// Source: ../sanity/queries/courses.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)]  | order(popular desc, title asc) {      _id,  title,  "slug": slug.current,  summary,  coverImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  icon {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  level,  price,  "popular": coalesce(popular, false),  "studentCount": coalesce(studentCount, 0),  category->{    _id,    title,    "slug": slug.current  },  instructor->{    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot }  },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[])  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  icon: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  level: "advanced" | "all-levels" | "beginner" | "intermediate";
  price: number;
  popular: boolean | false;
  studentCount: number;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string>;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    };
  };
  moduleCount: number;
  lessonCount: number;
}>;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  summary,  coverImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  icon {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  level,  price,  "popular": coalesce(popular, false),  "studentCount": coalesce(studentCount, 0),  category->{    _id,    title,    "slug": slug.current  },  instructor->{    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot }  },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),    learningOutcomes[] {      _key,      title,      description,      icon    },    modules[] {      _key,      title,      summary,      lessons[]->{          _id,  title,  "slug": slug.current,  poster {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  durationSeconds,  "freePreview": coalesce(freePreview, false),  "studentCount": coalesce(studentCount, 0),  keyPoints      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  icon: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  level: "advanced" | "all-levels" | "beginner" | "intermediate";
  price: number;
  popular: boolean | false;
  studentCount: number;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string>;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    };
  };
  moduleCount: number;
  lessonCount: number;
  learningOutcomes: Array<{
    _key: string;
    title: string;
    description: string;
    icon: string;
  }>;
  modules: Array<{
    _key: string;
    title: string;
    summary: string;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      poster: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      } | null;
      durationSeconds: number | null;
      freePreview: boolean | false;
      studentCount: number;
      keyPoints: Array<string> | null;
    }>;
  }>;
} | null;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },    "courseCount": count(*[      _type == "course" &&      instructor._ref == ^._id &&      defined(slug.current)    ])  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string>;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  courseCount: number;
}>;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    expertise,    bio,    photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },    "courses": *[      _type == "course" &&      instructor._ref == ^._id &&      defined(slug.current)    ] | order(popular desc, title asc) {        _id,  title,  "slug": slug.current,  summary,  coverImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  icon {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },  level,  price,  "popular": coalesce(popular, false),  "studentCount": coalesce(studentCount, 0),  category->{    _id,    title,    "slug": slug.current  },  instructor->{    _id,    name,    "slug": slug.current,    expertise,    photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot }  },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[])    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string>;
  bio: PortableText;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    };
    icon: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    level: "advanced" | "all-levels" | "beginner" | "intermediate";
    price: number;
    popular: boolean | false;
    studentCount: number;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string>;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      };
    };
    moduleCount: number;
    lessonCount: number;
  }>;
} | null;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    poster {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },    durationSeconds,    "freePreview": coalesce(freePreview, false),    "studentCount": coalesce(studentCount, 0),    notes,    keyPoints,    proTip,    resources[] {      _key,      type,      title,      description,      url    },    "course": *[      _type == "course" &&      defined(slug.current) &&      references(^._id)    ][0] {      _id,      title,      "slug": slug.current,      icon {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot },      instructor->{        _id,        name,        "slug": slug.current,        expertise,        photo {   asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot }      },      modules[] {        _key,        title,        summary,        lessons[]->{          _id,          title,          "slug": slug.current,          durationSeconds,          "freePreview": coalesce(freePreview, false)        }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  poster: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  durationSeconds: number | null;
  freePreview: boolean | false;
  studentCount: number;
  notes: PortableText;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "download" | "link" | "template";
    title: string;
    description: string;
    url: string;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    icon: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string>;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      };
    };
    modules: Array<{
      _key: string;
      title: string;
      summary: string;
      lessons: Array<{
        _id: string;
        title: string;
        slug: string;
        durationSeconds: number | null;
        freePreview: boolean | false;
      }>;
    }>;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"category\" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"courseCount\": count(*[\n      _type == \"course\" &&\n      category._ref == ^._id &&\n      defined(slug.current)\n    ])\n  }\n": CATEGORIES_QUERY_RESULT;
    "\n  *[_type == \"category\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"courses\": *[\n      _type == \"course\" &&\n      category._ref == ^._id &&\n      defined(slug.current)\n    ] | order(popular desc, title asc) {\n      \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  icon { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  level,\n  price,\n  \"popular\": coalesce(popular, false),\n  \"studentCount\": coalesce(studentCount, 0),\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n }\n  },\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[])\n\n    }\n  }\n": CATEGORY_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"course\" && defined(slug.current)]\n  | order(popular desc, title asc) {\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  icon { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  level,\n  price,\n  \"popular\": coalesce(popular, false),\n  \"studentCount\": coalesce(studentCount, 0),\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n }\n  },\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[])\n\n  }\n": COURSES_QUERY_RESULT;
    "\n  *[_type == \"course\" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  icon { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  level,\n  price,\n  \"popular\": coalesce(popular, false),\n  \"studentCount\": coalesce(studentCount, 0),\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n }\n  },\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[])\n,\n    learningOutcomes[] {\n      _key,\n      title,\n      description,\n      icon\n    },\n    modules[] {\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        \n  _id,\n  title,\n  \"slug\": slug.current,\n  poster { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  durationSeconds,\n  \"freePreview\": coalesce(freePreview, false),\n  \"studentCount\": coalesce(studentCount, 0),\n  keyPoints\n\n      }\n    }\n  }\n": COURSE_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n    \"courseCount\": count(*[\n      _type == \"course\" &&\n      instructor._ref == ^._id &&\n      defined(slug.current)\n    ])\n  }\n": INSTRUCTORS_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && slug.current == $slug][0] {\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    bio,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n    \"courses\": *[\n      _type == \"course\" &&\n      instructor._ref == ^._id &&\n      defined(slug.current)\n    ] | order(popular desc, title asc) {\n      \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  icon { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n  level,\n  price,\n  \"popular\": coalesce(popular, false),\n  \"studentCount\": coalesce(studentCount, 0),\n  category->{\n    _id,\n    title,\n    \"slug\": slug.current\n  },\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n }\n  },\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[])\n\n    }\n  }\n": INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"lesson\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    videoUrl,\n    poster { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n    durationSeconds,\n    \"freePreview\": coalesce(freePreview, false),\n    \"studentCount\": coalesce(studentCount, 0),\n    notes,\n    keyPoints,\n    proTip,\n    resources[] {\n      _key,\n      type,\n      title,\n      description,\n      url\n    },\n    \"course\": *[\n      _type == \"course\" &&\n      defined(slug.current) &&\n      references(^._id)\n    ][0] {\n      _id,\n      title,\n      \"slug\": slug.current,\n      icon { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n },\n      instructor->{\n        _id,\n        name,\n        \"slug\": slug.current,\n        expertise,\n        photo { \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n }\n      },\n      modules[] {\n        _key,\n        title,\n        summary,\n        lessons[]->{\n          _id,\n          title,\n          \"slug\": slug.current,\n          durationSeconds,\n          \"freePreview\": coalesce(freePreview, false)\n        }\n      }\n    }\n  }\n": LESSON_BY_SLUG_QUERY_RESULT;
  }
}

